FROM nginx:1.22.0

ENV TZ=UTC

# install
RUN apt-get update && \
    apt-get -y install sudo && \
    sudo apt-get install -y apache2-utils && \
    apt-get install -y openssl
# nginx config file
COPY ./docker/nginx/default.conf.local /etc/nginx/conf.d/default.conf
COPY ./docker/nginx/gen_htpasswd.sh /etc/nginx

RUN chmod 777 /etc/nginx/gen_htpasswd.sh
RUN /etc/nginx/gen_htpasswd.sh